language: node_js
node_js:
  - "8"

after_success:
  - ssh-keyscan -t rsa,dsa,ecdsa -H $DEPLOY_REPO_HOST 2>&1 | tee -a ${TRAVIS_HOME}/.ssh/known_hosts
  - git remote add deploy "$DEPLOY_REPO_USER@$DEPLOY_REPO_HOST:$DEPLOY_REPO_PATH"
  - git push deploy master
